podTemplate(
  label: 'parent',
  containers:
  [
    containerTemplate(name: 'kubectl', image: 'lachlanevenson/k8s-kubectl:v1.8.12', command: 'cat', ttyEnabled: true),
    containerTemplate(name: 'docker', image: 'docker', command: 'cat', ttyEnabled: true),
  ],
  volumes: [hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock')],
  serviceAccount: 'diamanti-jenkins-sa',
  namespace: 'jenkins')
{
  node ('parent')
  {
    try
    {
      stage('Clone repository')
      {
        /* Let's make sure we have the repository cloned to our workspace */
        checkout scm
      }
      stage('Show there is nothing running right now')
      {
        container('kubectl')
        {
          sh 'kubectl get pods -o wide'
        }
      }
      stage('Deploy Redis')
      {
        container('kubectl')
        {
          sh 'cd redis; sh run.sh'
        }
      }
      // stage('Create a Redis Cluster on Node 1')
      // {
      //   container('kubectl')
      //   {
      //     sh '''
      //     kubectl exec redis-enterprise-0 -it -- bash -c "sh /opt/cluster-create.sh"
      //     '''
      //   }
      // }
      // stage('Join the cluster from Node 2')
      // {
      //   container('kubectl')
      //   {
      //     sh '''
      //     kubectl exec redis-enterprise-1 -it -- bash -c "sh /opt/cluster-join.sh"
      //     '''
      //   }
      // }
    }
    finally
    {
      stage('Show we Deployed Redis')
      {
        container('kubectl')
        {
          sh 'kubectl get pods -o wide'
        }
      }
    }
  }
}
